const menuData = {
  code: 200,
  retDesc: '操作成功',
  // data: [
  //   {
  //     id: '001',
  //     parentId: '0',
  //     parentIds: '0',
  //     menuName: '内容管理',
  //     menuIcon: 'el-icon-document-copy',
  //     sortNo: 11231,
  //     menuUrl: '/knowledge'
  //   },
  //   {
  //     id: '001001',
  //     parentId: '001',
  //     parentIds: '0,001',
  //     menuName: '内容体系管理',
  //     menuIcon: '',
  //     sortNo: 11231,
  //     menuUrl: '/knowledge/category'
  //   },
  //   {
  //     id: '001002',
  //     parentId: '001',
  //     parentIds: '0,001',
  //     menuName: '宣教内容管理',
  //     menuIcon: '',
  //     sortNo: 11231,
  //     menuUrl: '/knowledge/content'
  //   },
  //   {
  //     id: '001002001',
  //     parentId: '001002',
  //     parentIds: '0,001,001002',
  //     menuName: '宣教内容管理',
  //     menuIcon: '',
  //     sortNo: 11231,
  //     menuUrl: '/knowledge/content/edit',
  //     isShow: false
  //   },

  //   {
  //     id: '003',
  //     parentId: '0',
  //     parentIds: '0',
  //     menuName: '展示规则管理',
  //     menuIcon: 'el-icon-receiving',
  //     sortNo: 11231,
  //     menuUrl: '/display'
  //   },
  //   {
  //     id: '003002',
  //     parentId: '003',
  //     parentIds: '0,003',
  //     menuName: '宣教展示设定',
  //     menuIcon: '',
  //     sortNo: 11231,
  //     menuUrl: '/display/content'
  //   },

  //   {
  //     id: '005',
  //     parentId: '0',
  //     parentIds: '0',
  //     menuName: '检索规则管理',
  //     menuIcon: 'el-icon-notebook-1',
  //     sortNo: 11231,
  //     menuUrl: '/search'
  //   },
  //   {
  //     id: '005001',
  //     parentId: '005',
  //     parentIds: '0,005',
  //     menuName: '标签管理',
  //     menuIcon: '',
  //     sortNo: 11231,
  //     menuUrl: '/search/tag'
  //   },

  //   {
  //     id: '004',
  //     parentId: '0',
  //     parentIds: '0',
  //     menuName: '系统管理',
  //     menuIcon: 'ui-icon-line-currency-setting',
  //     sortNo: 11231,
  //     menuUrl: '/settings'
  //   },
  //   {
  //     id: '004002',
  //     parentId: '004',
  //     parentIds: '0,004',
  //     menuName: '部门管理',
  //     menuIcon: '',
  //     sortNo: 11231,
  //     menuUrl: '/settings/department'
  //   },
  //   {
  //     id: '004003',
  //     parentId: '004',
  //     parentIds: '0,004',
  //     menuName: '账号管理',
  //     menuIcon: '',
  //     sortNo: 11231,
  //     menuUrl: '/settings/user'
  //   }
  // ],
  data: [{
      "resourceId": 1,
      "parentId": 0,
      "name": "内容管理",
      "permits": "knowledge",
      "type": 1,
      "url": "/knowledge",
      "layer": 1,
      "idx": 1,
      "icon": "el-icon-document-copy",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2017-10-07T17:01:14",
      "createTime": "2017-10-07T17:01:14",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 3,
      "parentId": 0,
      "name": "展示规则管理",
      "permits": "display",
      "type": 1,
      "url": "/display",
      "layer": 1,
      "idx": 2,
      "icon": "el-icon-receiving",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2020-11-02T23:34:16",
      "createTime": "2020-11-02T23:34:20",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 4,
      "parentId": 0,
      "name": "系统管理",
      "permits": "settings",
      "type": 1,
      "url": "/settings",
      "layer": 1,
      "idx": 4,
      "icon": "ui-icon-line-currency-setting",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2020-11-02T23:37:46",
      "createTime": "2020-11-02T23:37:49",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 5,
      "parentId": 0,
      "name": "检索规则管理",
      "permits": "search",
      "type": 1,
      "url": "/search",
      "layer": 1,
      "idx": 3,
      "icon": "el-icon-notebook-1",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2020-11-02T23:57:31",
      "createTime": "2020-11-02T23:57:35",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 1001,
      "parentId": 1,
      "name": "内容体系管理",
      "permits": "knowledge:category",
      "type": 1,
      "url": "/knowledge/category",
      "layer": 2,
      "idx": 1,
      "icon": "",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2017-10-07T17:32:39",
      "createTime": "2017-10-07T17:03:17",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 1002,
      "parentId": 1,
      "name": "宣教内容管理",
      "permits": "knowledge:content",
      "type": 1,
      "url": "/knowledge/content",
      "layer": 2,
      "idx": 2,
      "icon": "",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2017-10-07T17:32:55",
      "createTime": "2017-10-07T17:24:42",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 3002,
      "parentId": 3,
      "name": "宣教展示设定",
      "permits": "display:content",
      "type": 1,
      "url": "/display/content",
      "layer": 2,
      "idx": 1,
      "icon": "",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2020-11-02T23:37:39",
      "createTime": "2020-11-02T23:37:43",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 4002,
      "parentId": 4,
      "name": "部门管理",
      "permits": "settings:department",
      "type": 1,
      "url": "/settings/department",
      "layer": 2,
      "idx": 1,
      "icon": "",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2020-11-02T23:39:35",
      "createTime": "2020-11-02T23:39:39",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 4003,
      "parentId": 4,
      "name": "账号管理",
      "permits": "settings:user",
      "type": 1,
      "url": "/settings/user",
      "layer": 2,
      "idx": 3,
      "icon": "",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2020-11-02T23:40:45",
      "createTime": "2020-11-02T23:40:48",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    },
    {
      "resourceId": 5001,
      "parentId": 5,
      "name": "标签管理",
      "permits": "search:tag",
      "type": 1,
      "url": "/search/tag",
      "layer": 2,
      "idx": 1,
      "icon": "",
      "description": "",
      "isHided": 0,
      "isDeleted": 0,
      "modifiedTime": "2020-11-02T23:58:33",
      "createTime": "2020-11-02T23:58:35",
      "children": null,
      "selected": null,
      "childSelected": null,
      "parentName": null
    }
  ]
}

export default menuData
